### ISSUE TITLE
Change CloudFormation import command

### ISSUE THREAD

**Issue by stephendv1** [iriusrisk/iriusrisk-cli#13]
Currently CF can be imported into a new product using this command:
irius product create [-cf=<CF Template>] [-i=<product unique ID>]
                            [-mf=<Mapping File>] [-n=<product name>]
                            [-p=<Parameters>]

Change the "create" command to an "import" command:
irius product import -type=cf -f=<CF Template File> -i=<product unique ID>]
                            [-mf=<Mapping File>] [-n=<product name>]
                            [-p=<Parameters>]
The description for the "import" command should be: Create a new product in IriusRisk from an external model format.  Currently supported formats are: AWS CloudFormation.

**Comment by jahtoe** [comment]
Main is updated with those changes.

Also added, for phase one only, parameters to set the graph width and height and the trustzone width and height. I've spoken with Paul on this. Phase two we expect to remove these parameters in favour of automated size determination. For now it's useful towards producing better looking outputs.

java -jar irius-cli-1.0-jar-with-dependencies.jar product import -type cf -n Example11.yaml -i Example11.yaml -f  "Example11.yaml" -mf "iriusrisk-mapping.yaml" -p "KeyPair=NODEFAULTSET" -d "true" -tzh 600 -tzw 600 -gh 600 -gw 2500
