### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by stephendv1** [iriusrisk/iriusrisk-cli#2]
The base package name should be: com.iriusrisk.cli.

**Comment by dFarras** [comment]
![image](https://user-images.githubusercontent.com/28202081/104018561-45b21e00-51ba-11eb-8141-c23dd513a8b8.png)
There are still old package names as you can see in the image

**Comment by lukacupic** [comment]
The issue should be resolved now with [this merge](https://github.com/iriusrisk/iriusrisk-cli/commit/ac5341f4160daabd16de8015d5f366641802dfdd).
