### ISSUE TITLE
JSON mapping

### ISSUE THREAD

**Issue by dFarras** [iriusrisk/iriusrisk-cli#4]
Actually, at CredentialUtils, we have to read some information from a file and print it as a JSON.
Since the information is not written as a JSON we are forced to map it on the fly to print it on the desired format. To avoid this problem we should be using Jackson.

For this task  to be implemented four points must be completed:
- Credentials must be modeled, there has to be an object describing every of its elements. (This will make it easier to validate them before writing)
- Whenever any information is written in credentials file it should be done using Jackson so that it is written directly in JSON format
- Whenever credentials are retrieved it must be done directly from Jackson's API, it will return you the object that models credentials
- To convert Credentials object to a String (in order to print it) Jackson should be invoked

There are other mappers out there for Java but Jackson is the standard since it is declared as Spring's standard.

**Comment by lukacupic** [comment]
Hi Diego,

Can you please elaborate on how you planned to model the credentials? Should it be one Credentials class containing all credentials? Or each credential separately in its own Credential class?

**Comment by dFarras** [comment]
Just one class modeling the credentials so that you can read all credentials as one java object in a single operation.

```
Public class Credentials {
    private String apiToken;
    //Getters, setters...
}
```

And then from jackson you can read them into that model by doing something like (the method does not have that exact name but I am writing this from memory):
`jackson.readValue(Paths.get(path-to-file), Credentials.class)`

**Comment by lukacupic** [comment]
@dFarras Could you please verify if this issue has been resolved?
Thanks
